// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_ParameterlessConstructor_SetsLineWidthPropertyToOnePointZero")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_ParameterlessConstructor_SetsFillerDashLineWidthPropertyToZeroPointFive")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsDifferentObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectDisplayBoxHoursProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectDisplayCreditsProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectDisplayGlossaryProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectDisplayGraphProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectDisplayLocoDiagramRowProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectDisplayLocoToWorkRowProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectDisplayToWorkRowProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectExportEngineProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectFillerDashLineWidthProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_CopyMethod_ReturnsObjectWithCorrectLineWidthProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.DocumentExportOptionsUnitTests.DocumentExportOptionsClass_ParameterlessConstructor_SetsExportEnginePropertyToExternal")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.Display.TimetableSectionModelUnitTests.TimetableSectionModelClass_AddMethod_ThrowsArgumentNullExceptionIfParameterIsNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.Display.TimetableSectionModelUnitTests.TimetableSectionModelClass_AddMethod_ThrowsArgumentNullExceptionWithCorrectParamNamePropertyIfParameterIsNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.Display.TrainSegmentModelUnitTests.TrainSegmentModelClass_ConstructorWithTrainAndListOfILocationEntryParameters_ThrowsArgumentNullExceptionIfFirstParameterIsNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.Data.Tests.Unit.Display.TrainSegmentModelUnitTests.TrainSegmentModelClass_ConstructorWithTrainAndListOfILocationEntryParameters_ThrowsArgumentNullExceptionWithCorrectParamNamePropertyIfFirstParameterIsNull")]