//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabler.PdfExport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Content\\Fonts")]
        public string FontFolder {
            get {
                return ((string)(this["FontFolder"]));
            }
            set {
                this["FontFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CharisSIL-R.ttf")]
        public string SerifRomanFace {
            get {
                return ((string)(this["SerifRomanFace"]));
            }
            set {
                this["SerifRomanFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CharisSIL-I.ttf")]
        public string SerifItalicFace {
            get {
                return ((string)(this["SerifItalicFace"]));
            }
            set {
                this["SerifItalicFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CharisSIL-B.ttf")]
        public string SerifBoldFace {
            get {
                return ((string)(this["SerifBoldFace"]));
            }
            set {
                this["SerifBoldFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CharisSIL-BI.ttf")]
        public string SerifBoldItalicFace {
            get {
                return ((string)(this["SerifBoldItalicFace"]));
            }
            set {
                this["SerifBoldItalicFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Heebo-Regular.ttf")]
        public string SansRomanFace {
            get {
                return ((string)(this["SansRomanFace"]));
            }
            set {
                this["SansRomanFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Heebo-Bold.ttf")]
        public string SansBoldFace {
            get {
                return ((string)(this["SansBoldFace"]));
            }
            set {
                this["SansBoldFace"] = value;
            }
        }
    }
}
