//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabler.PdfExport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timetabler.PdfExport.LogMessageResources", typeof(LogMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold body offset is {0}.
        /// </summary>
        internal static string LogMessage_BoldBodyOffset {
            get {
                return ResourceManager.GetString("LogMessage_BoldBodyOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing location list.  Font ascent is {1}..
        /// </summary>
        internal static string LogMessage_DrawingLocationList {
            get {
                return ResourceManager.GetString("LogMessage_DrawingLocationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing separator from {0}, {1} to {2}, {3}.
        /// </summary>
        internal static string LogMessage_DrawingSeparator {
            get {
                return ResourceManager.GetString("LogMessage_DrawingSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifting Y coord by {0}.
        /// </summary>
        internal static string LogMessage_IncreasingYCoordinate {
            get {
                return ResourceManager.GetString("LogMessage_IncreasingYCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are we to include a loco diagram row? {0}.
        /// </summary>
        internal static string LogMessage_IsLocoDiagramRowIncluded {
            get {
                return ResourceManager.GetString("LogMessage_IsLocoDiagramRowIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic body offset is {0}.
        /// </summary>
        internal static string LogMessage_ItalicBodyOffset {
            get {
                return ResourceManager.GetString("LogMessage_ItalicBodyOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page margins are T: {0}, B: {1}, L: {2}, R: {3}.
        /// </summary>
        internal static string LogMessage_PageMargins {
            get {
                return ResourceManager.GetString("LogMessage_PageMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain body offset is {0}.
        /// </summary>
        internal static string LogMessage_PlainBodyOffset {
            get {
                return ResourceManager.GetString("LogMessage_PlainBodyOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location {0} is a routing code row..
        /// </summary>
        internal static string LogMessage_RowIsARoutingCodeRow {
            get {
                return ResourceManager.GetString("LogMessage_RowIsARoutingCodeRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location {0} is not a routing code row..
        /// </summary>
        internal static string LogMessage_RowIsNotARoutingCodeRow {
            get {
                return ResourceManager.GetString("LogMessage_RowIsNotARoutingCodeRow", resourceCulture);
            }
        }
    }
}
