//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabler.PdfExport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timetabler.PdfExport.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked By.
        /// </summary>
        internal static string CheckedByCaption {
            get {
                return ResourceManager.GetString("CheckedByCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWN.
        /// </summary>
        internal static string DownSectionName {
            get {
                return ResourceManager.GetString("DownSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation Of Footnotes.
        /// </summary>
        internal static string GlossaryTitle {
            get {
                return ResourceManager.GetString("GlossaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ..
        /// </summary>
        internal static string LocationFillerDotPattern {
            get {
                return ResourceManager.GetString("LocationFillerDotPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco To Work.
        /// </summary>
        internal static string LocoToWorkRowCaption {
            get {
                return ResourceManager.GetString("LocoToWorkRowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string PublishedDateCaption {
            get {
                return ResourceManager.GetString("PublishedDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . ..
        /// </summary>
        internal static string RowEmptyCellAlternateFiller {
            get {
                return ResourceManager.GetString("RowEmptyCellAlternateFiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . . . ..
        /// </summary>
        internal static string RowEmptyCellFiller {
            get {
                return ResourceManager.GetString("RowEmptyCellFiller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set To Work.
        /// </summary>
        internal static string SetToWorkRowCaption {
            get {
                return ResourceManager.GetString("SetToWorkRowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Work.
        /// </summary>
        internal static string ToWorkRowCaption {
            get {
                return ResourceManager.GetString("ToWorkRowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        internal static string UpSectionName {
            get {
                return ResourceManager.GetString("UpSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionCaption {
            get {
                return ResourceManager.GetString("VersionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written By.
        /// </summary>
        internal static string WrittenByCaption {
            get {
                return ResourceManager.GetString("WrittenByCaption", resourceCulture);
            }
        }
    }
}
