//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabler.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timetabler.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination array does not contain enough elements to store the collection..
        /// </summary>
        internal static string BaseCollection_CopyTo_Error_InsufficientArrayLength {
            get {
                return ResourceManager.GetString("BaseCollection_CopyTo_Error_InsufficientArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format string {0} is not supported..
        /// </summary>
        internal static string Distance_ToString_FormatExceptionMessage {
            get {
                return ResourceManager.GetString("Distance_ToString_FormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plat.
        /// </summary>
        internal static string LocationRow_Abbreviation_Platform {
            get {
                return ResourceManager.GetString("LocationRow_Abbreviation_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding location arrival/departure row for {0}.
        /// </summary>
        internal static string LogMessage_AddArrivalDepartureRow {
            get {
                return ResourceManager.GetString("LogMessage_AddArrivalDepartureRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding routing code row for {0}.
        /// </summary>
        internal static string LogMessage_AddRoutingRow {
            get {
                return ResourceManager.GetString("LogMessage_AddRoutingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering ProcessTrain() for {0}.
        /// </summary>
        internal static string LogMessage_ProcessTrain {
            get {
                return ResourceManager.GetString("LogMessage_ProcessTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        internal static string SignalboxHours_TokenBalanceWarningSymbol {
            get {
                return ResourceManager.GetString("SignalboxHours_TokenBalanceWarningSymbol", resourceCulture);
            }
        }
    }
}
