using System.Collections.Generic;
using System.Linq;

namespace Unicorn.FontTools.Afm2Code
{
    internal class ClassCoder
    {
        private string Namespace { get; set; }
        private string ClassName { get; set; }

        internal ClassCoder(string nameSpace, string className)
        {
            Namespace = nameSpace;
            ClassName = className;
        }

        internal string OutputStart(IEnumerable<string> fileNames)
        {
            string output = $"// This file was generated by {GetType().Assembly.FullName}\n";
            if (fileNames != null)
            {
                string[] names = fileNames.ToArray();
                if (names.Length > 0)
                {
                    output += "// The code was generated from the following files:\n";
                    foreach (string n in names)
                    {
                        output += $"//      {n}\n";
                    }
                }
                output += "// Please regenerate this file instead of editing it by hand.\n\n";
            }
            return $"namespace {Namespace}\n{{\n    public static class {ClassName}\n    {{\n";
        }

        internal string OutputEnd()
        {
            return "    }\n}\n";
        }
    }
}
