// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsDocumentDescriptorClassInstance_IfConstructorParameterWasEqualToExternal")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsPdfDocumentClassInstance_IfConstructorParameterWasEqualToUnicorn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsPdfDocumentClassInstanceWithDefaultHorizontalMarginProportionEqualToFirstParameter_IfConstructorParameterWasEqualToExternal")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsPdfDocumentClassInstanceWithDefaultHorizontalMarginProportionEqualToFirstParameter_IfConstructorParameterWasEqualToUnicorn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsPdfDocumentClassInstanceWithDefaultPageOrientationEqualToLandscape_IfConstructorParameterWasEqualToExternal")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsPdfDocumentClassInstanceWithDefaultPageOrientationEqualToLandscape_IfConstructorParameterWasEqualToUnicorn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsPdfDocumentClassInstanceWithDefaultPageSizeEqualToA4_IfConstructorParameterWasEqualToExternal")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsPdfDocumentClassInstanceWithDefaultPageSizeEqualToA4_IfConstructorParameterWasEqualToUnicorn")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsPdfDocumentClassInstanceWithDefaultVerticalMarginProportionEqualToSecondParameter_IfConstructorParameterWasEqualToExternal")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:Timetabler.PdfExport.Tests.Unit.DocumentDescriptorFactoryUnitTests.DocumentDescriptorFactoryClass_GetDocumentDescriptorMethod_ReturnsPdfDocumentClassInstanceWithDefaultVerticalMarginProportionEqualToSecondParameter_IfConstructorParameterWasEqualToUnicorn")]
