//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timetabler.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string HumanReadableEnum_AddSubtract_Add {
            get {
                return ResourceManager.GetString("HumanReadableEnum_AddSubtract_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        internal static string HumanReadableEnum_AddSubtract_Subtract {
            get {
                return ResourceManager.GetString("HumanReadableEnum_AddSubtract_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival.
        /// </summary>
        internal static string HumanReadableEnum_ArrivalDeparture_Arrival {
            get {
                return ResourceManager.GetString("HumanReadableEnum_ArrivalDeparture_Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure.
        /// </summary>
        internal static string HumanReadableEnum_ArrivalDeparture_Departure {
            get {
                return ResourceManager.GetString("HumanReadableEnum_ArrivalDeparture_Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-Hour Clock.
        /// </summary>
        internal static string HumanReadableEnum_ClockType_12Hour {
            get {
                return ResourceManager.GetString("HumanReadableEnum_ClockType_12Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-Hour Clock.
        /// </summary>
        internal static string HumanReadableEnum_ClockType_24Hour {
            get {
                return ResourceManager.GetString("HumanReadableEnum_ClockType_24Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashed.
        /// </summary>
        internal static string HumanReadableEnum_DashStyle_Dash {
            get {
                return ResourceManager.GetString("HumanReadableEnum_DashStyle_Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash-Dot.
        /// </summary>
        internal static string HumanReadableEnum_DashStyle_DashDot {
            get {
                return ResourceManager.GetString("HumanReadableEnum_DashStyle_DashDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash-Dot-Dot.
        /// </summary>
        internal static string HumanReadableEnum_DashStyle_DashDotDot {
            get {
                return ResourceManager.GetString("HumanReadableEnum_DashStyle_DashDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotted.
        /// </summary>
        internal static string HumanReadableEnum_DashStyle_Dot {
            get {
                return ResourceManager.GetString("HumanReadableEnum_DashStyle_Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        internal static string HumanReadableEnum_DashStyle_Solid {
            get {
                return ResourceManager.GetString("HumanReadableEnum_DashStyle_Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free edit.
        /// </summary>
        internal static string HumanReadableEnum_GraphEditStyle_Free {
            get {
                return ResourceManager.GetString("HumanReadableEnum_GraphEditStyle_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not alter section times when editing.
        /// </summary>
        internal static string HumanReadableEnum_GraphEditStyle_PreserveSectionTimes {
            get {
                return ResourceManager.GetString("HumanReadableEnum_GraphEditStyle_PreserveSectionTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.m..
        /// </summary>
        internal static string HumanReadableEnum_HalfOfDay_AM {
            get {
                return ResourceManager.GetString("HumanReadableEnum_HalfOfDay_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.m..
        /// </summary>
        internal static string HumanReadableEnum_HalfOfDay_PM {
            get {
                return ResourceManager.GetString("HumanReadableEnum_HalfOfDay_PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condensed.
        /// </summary>
        internal static string HumanReadableEnum_LocationFontType_Condensed {
            get {
                return ResourceManager.GetString("HumanReadableEnum_LocationFontType_Condensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string HumanReadableEnum_LocationFontType_Normal {
            get {
                return ResourceManager.GetString("HumanReadableEnum_LocationFontType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        internal static string HumanReadableEnum_PdfExportEngine_External {
            get {
                return ResourceManager.GetString("HumanReadableEnum_PdfExportEngine_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicorn.
        /// </summary>
        internal static string HumanReadableEnum_PdfExportEngine_Unicorn {
            get {
                return ResourceManager.GetString("HumanReadableEnum_PdfExportEngine_Unicorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chainage must be a number..
        /// </summary>
        internal static string LocationEditForm_Chainage_ValidationFailureNaN {
            get {
                return ResourceManager.GetString("LocationEditForm_Chainage_ValidationFailureNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chainage must be a number between 0 and 80..
        /// </summary>
        internal static string LocationEditForm_Chainage_ValidationFailureOutOfRange {
            get {
                return ResourceManager.GetString("LocationEditForm_Chainage_ValidationFailureOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mileage must be a number..
        /// </summary>
        internal static string LocationEditForm_Mileage_ValidationFailureNaN {
            get {
                return ResourceManager.GetString("LocationEditForm_Mileage_ValidationFailureNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed..
        /// </summary>
        internal static string MainForm_Export_Completed {
            get {
                return ResourceManager.GetString("MainForm_Export_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred exporting to PDF file {0}.
        ///
        ///Error type: {1}
        ///Detail message: {2}.
        /// </summary>
        internal static string MainForm_FileExport_Failure {
            get {
                return ResourceManager.GetString("MainForm_FileExport_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be saved because it is open in another program..
        /// </summary>
        internal static string MainForm_FileExport_SharingViolation {
            get {
                return ResourceManager.GetString("MainForm_FileExport_SharingViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainForm_FileExport_SharingViolationTitle {
            get {
                return ResourceManager.GetString("MainForm_FileExport_SharingViolationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes.  Do you really want to start a new document?.
        /// </summary>
        internal static string MainForm_FileNew_UnsavedChanges {
            get {
                return ResourceManager.GetString("MainForm_FileNew_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred opening the file {2}.
        ///
        ///Error type: {0}
        ///Detail message: {1}.
        /// </summary>
        internal static string MainForm_FileOpen_Failure {
            get {
                return ResourceManager.GetString("MainForm_FileOpen_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes.  Do you really want to open a different file?.
        /// </summary>
        internal static string MainForm_FileOpen_UnsavedChanges {
            get {
                return ResourceManager.GetString("MainForm_FileOpen_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred saving the file {2}.
        ///
        ///Error type: {0}
        ///Detail message: {1}.
        /// </summary>
        internal static string MainForm_FileSave_Failure {
            get {
                return ResourceManager.GetString("MainForm_FileSave_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be saved because it is open in another program..
        /// </summary>
        internal static string MainForm_FileSave_SharingViolation {
            get {
                return ResourceManager.GetString("MainForm_FileSave_SharingViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainForm_FileSave_SharingViolationTitle {
            get {
                return ResourceManager.GetString("MainForm_FileSave_SharingViolationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes.  Do you really want to exit?.
        /// </summary>
        internal static string MainForm_FormClosing_UnsavedChanges {
            get {
                return ResourceManager.GetString("MainForm_FormClosing_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string MainForm_FormClosing_UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("MainForm_FormClosing_UnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred opening the file {0}.
        ///
        ///Error type: {1}
        ///Detail message: {2}.
        /// </summary>
        internal static string MainForm_LocationsTemplateFileLoad_Exception {
            get {
                return ResourceManager.GetString("MainForm_LocationsTemplateFileLoad_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: the template file could not be loaded..
        /// </summary>
        internal static string MainForm_LocationsTemplateFileLoad_NullObject {
            get {
                return ResourceManager.GetString("MainForm_LocationsTemplateFileLoad_NullObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainForm_LocationsTemplateFileLoad_NullObjectTitle {
            get {
                return ResourceManager.GetString("MainForm_LocationsTemplateFileLoad_NullObjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will replace all of the location data in the current file with location data from the selected template.
        ///
        ///If trains in the current document refer to locations that are not present in the new template,
        ///those trains may no longer be editable.
        ///
        ///Do you want to proceed?.
        /// </summary>
        internal static string MainForm_LocationsTemplateFileLoad_Warning {
            get {
                return ResourceManager.GetString("MainForm_LocationsTemplateFileLoad_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Current Locations.
        /// </summary>
        internal static string MainForm_LocationsTemplateFileLoad_WarningTitle {
            get {
                return ResourceManager.GetString("MainForm_LocationsTemplateFileLoad_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current locations list has been saved as a template..
        /// </summary>
        internal static string MainForm_LocationsTemplateFileSave_Success {
            get {
                return ResourceManager.GetString("MainForm_LocationsTemplateFileSave_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations Saved.
        /// </summary>
        internal static string MainForm_LocationsTemplateFileSave_Title {
            get {
                return ResourceManager.GetString("MainForm_LocationsTemplateFileSave_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred opening the file {0}..
        /// </summary>
        internal static string MainForm_TemplateFileLoad_Exception {
            get {
                return ResourceManager.GetString("MainForm_TemplateFileLoad_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: the template file could not be loaded..
        /// </summary>
        internal static string MainForm_TemplateFileLoad_NullObject {
            get {
                return ResourceManager.GetString("MainForm_TemplateFileLoad_NullObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainForm_TemplateFileLoad_NullObjectTitle {
            get {
                return ResourceManager.GetString("MainForm_TemplateFileLoad_NullObjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be saved because it is open in another program..
        /// </summary>
        internal static string MainForm_TemplateFileSave_SharingViolation {
            get {
                return ResourceManager.GetString("MainForm_TemplateFileSave_SharingViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainForm_TemplateFileSave_SharingViolationTitle {
            get {
                return ResourceManager.GetString("MainForm_TemplateFileSave_SharingViolationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCO TO WORK.
        /// </summary>
        internal static string MainForm_TimetableGridView_LocoToWorkRowName {
            get {
                return ResourceManager.GetString("MainForm_TimetableGridView_LocoToWorkRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TO WORK.
        /// </summary>
        internal static string MainForm_TimetableGridView_SetToWorkRowName {
            get {
                return ResourceManager.GetString("MainForm_TimetableGridView_SetToWorkRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO WORK.
        /// </summary>
        internal static string MainForm_TimetableGridView_ToWorkRowName {
            get {
                return ResourceManager.GetString("MainForm_TimetableGridView_ToWorkRowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        internal static string SignalboxHoursEditForm_Signalbox_Name_Unknown {
            get {
                return ResourceManager.GetString("SignalboxHoursEditForm_Signalbox_Name_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn start and end time data, if provided, must consist of numbers only..
        /// </summary>
        internal static string SignalboxHoursEditForm_ValidateTimes_Error {
            get {
                return ResourceManager.GetString("SignalboxHoursEditForm_ValidateTimes_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset must be a positive whole number..
        /// </summary>
        internal static string TrainAdjustTimesForm_Offset_ValidationFailure {
            get {
                return ResourceManager.GetString("TrainAdjustTimesForm_Offset_ValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offset must be a positive whole number..
        /// </summary>
        internal static string TrainCopyForm_Offset_ValidationFailure {
            get {
                return ResourceManager.GetString("TrainCopyForm_Offset_ValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying train {0}.
        /// </summary>
        internal static string TrainCopyForm_TrainHeadcode_FormatString {
            get {
                return ResourceManager.GetString("TrainCopyForm_TrainHeadcode_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The train you are editing has no timing points.  Trains must have timing points to appear in the timetable.
        ///
        ///If you press &quot;OK&quot; your edit will be discarded.  If you press &quot;Cancel&quot; you can continue editing the train..
        /// </summary>
        internal static string TrainEditForm_NoTimingPoints_Warning {
            get {
                return ResourceManager.GetString("TrainEditForm_NoTimingPoints_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Timing Points.
        /// </summary>
        internal static string TrainEditForm_NoTimingPoints_WarningTitle {
            get {
                return ResourceManager.GetString("TrainEditForm_NoTimingPoints_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing data, if provided, must consist of numbers only..
        /// </summary>
        internal static string TrainLocationTimeEditForm_ValidateTimes_Error {
            get {
                return ResourceManager.GetString("TrainLocationTimeEditForm_ValidateTimes_Error", resourceCulture);
            }
        }
    }
}
