//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timetabler.DataLoader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Timetabler.DataLoader.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create XML reader..
        /// </summary>
        internal static string Error_CouldNotCreateXmlReader {
            get {
                return ResourceManager.GetString("Error_CouldNotCreateXmlReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty time of day could not be parsed..
        /// </summary>
        internal static string Error_EmptyTime {
            get {
                return ResourceManager.GetString("Error_EmptyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception occurred in loader..
        /// </summary>
        internal static string Error_GenericLoaderError {
            get {
                return ResourceManager.GetString("Error_GenericLoaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of day could not be parsed..
        /// </summary>
        internal static string Error_TimeUnparseable {
            get {
                return ResourceManager.GetString("Error_TimeUnparseable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not contain &lt;DocumentModel&gt;..
        /// </summary>
        internal static string Error_XmlDoesNotContainDocumentModel {
            get {
                return ResourceManager.GetString("Error_XmlDoesNotContainDocumentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not contain &lt;LocationTemplateModel&gt;..
        /// </summary>
        internal static string Error_XmlDoesNotContainLocationTemplateModel {
            get {
                return ResourceManager.GetString("Error_XmlDoesNotContainLocationTemplateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not contain &lt;TimetableDocumentTemplate&gt;..
        /// </summary>
        internal static string Error_XmlDoesNotContainTimetableDocumentTemplate {
            get {
                return ResourceManager.GetString("Error_XmlDoesNotContainTimetableDocumentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DocumentModel&gt; element does not specify version number..
        /// </summary>
        internal static string Error_XmlDoesNotSpecifyVersion {
            get {
                return ResourceManager.GetString("Error_XmlDoesNotSpecifyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files are no longer supported..
        /// </summary>
        internal static string Error_XmlLoaderError {
            get {
                return ResourceManager.GetString("Error_XmlLoaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LocationTemplateModel&gt; element does not specify version number..
        /// </summary>
        internal static string Error_XmlLocationTemplateDoesNotSpecifyVersion {
            get {
                return ResourceManager.GetString("Error_XmlLocationTemplateDoesNotSpecifyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LocationTemplateModel&gt; version {0} is too high to be supported..
        /// </summary>
        internal static string Error_XmlLocationTemplateUnsupportedVersion {
            get {
                return ResourceManager.GetString("Error_XmlLocationTemplateUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TimetableDocumentTemplate&gt; element does not specify version number..
        /// </summary>
        internal static string Error_XmlTimetableDocumentTemplateDoesNotSpecifyVersion {
            get {
                return ResourceManager.GetString("Error_XmlTimetableDocumentTemplateDoesNotSpecifyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TimetableDocumentTemplate&gt; version {0} is too high to be supported..
        /// </summary>
        internal static string Error_XmlTimetableDocumentTemplateUnsupportedVersion {
            get {
                return ResourceManager.GetString("Error_XmlTimetableDocumentTemplateUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DocumentModel&gt; version {0} is too high to be supported..
        /// </summary>
        internal static string Error_XmlUnsupportedVersion {
            get {
                return ResourceManager.GetString("Error_XmlUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} locations to load..
        /// </summary>
        internal static string LogMessage_LocationCount {
            get {
                return ResourceManager.GetString("LogMessage_LocationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} locations..
        /// </summary>
        internal static string LogMessage_LocationsLoaded {
            get {
                return ResourceManager.GetString("LogMessage_LocationsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} note definitions to load..
        /// </summary>
        internal static string LogMessage_NoteDefinitionCount {
            get {
                return ResourceManager.GetString("LogMessage_NoteDefinitionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} note definitions..
        /// </summary>
        internal static string LogMessage_NoteDefinitionsLoaded {
            get {
                return ResourceManager.GetString("LogMessage_NoteDefinitionsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} signalboxes to load..
        /// </summary>
        internal static string LogMessage_SignalboxCount {
            get {
                return ResourceManager.GetString("LogMessage_SignalboxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} signalboxes..
        /// </summary>
        internal static string LogMessage_SignalboxesLoaded {
            get {
                return ResourceManager.GetString("LogMessage_SignalboxesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} signalbox hours sets to load..
        /// </summary>
        internal static string LogMessage_SignalboxHoursSetCount {
            get {
                return ResourceManager.GetString("LogMessage_SignalboxHoursSetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} signalbox hours sets..
        /// </summary>
        internal static string LogMessage_SignalboxHoursSetsLoaded {
            get {
                return ResourceManager.GetString("LogMessage_SignalboxHoursSetsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting TimetableFileModel to TimetableDocument, file version {0}.
        /// </summary>
        internal static string LogMessage_TimetableFileModelConversionVersion {
            get {
                return ResourceManager.GetString("LogMessage_TimetableFileModelConversionVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} train classes to load..
        /// </summary>
        internal static string LogMessage_TrainClassCount {
            get {
                return ResourceManager.GetString("LogMessage_TrainClassCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} train classes..
        /// </summary>
        internal static string LogMessage_TrainClassesLoaded {
            get {
                return ResourceManager.GetString("LogMessage_TrainClassesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} trains to load..
        /// </summary>
        internal static string LogMessage_TrainCount {
            get {
                return ResourceManager.GetString("LogMessage_TrainCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} trains..
        /// </summary>
        internal static string LogMessage_TrainsLoaded {
            get {
                return ResourceManager.GetString("LogMessage_TrainsLoaded", resourceCulture);
            }
        }
    }
}
