// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Unicorn.Impl.PdfSharp.Tests.Unit.FontDescriptorUnitTests.FontDescriptorClass_GetNormalSpaceWidthMethod_CallsMeasureStringMethodOfParameter_IfParameterIsNotNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Unicorn.Impl.PdfSharp.Tests.Unit.FontDescriptorUnitTests.FontDescriptorClass_GetNormalSpaceWidthMethod_CallsMeasureStringMethodOfParameterWithFirstParameterEqualToSpace_IfParameterIsNotNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Unicorn.Impl.PdfSharp.Tests.Unit.FontDescriptorUnitTests.FontDescriptorClass_GetNormalSpaceWidthMethod_CallsMeasureStringMethodOfParameterWithSecondParameterEqualToItself_IfParameterIsNotNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Unicorn.Impl.PdfSharp.Tests.Unit.FontDescriptorUnitTests.FontDescriptorClass_GetNormalSpaceWidthMethod_ReturnsWidthPropertyOfObjectReturnedByMeasureStringMethodOfParameter_IfParameterIsNotNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Unicorn.Impl.PdfSharp.Tests.Unit.FontDescriptorUnitTests.FontDescriptorClass_GetNormalSpaceWidthMethod_ThrowsArgumentNullException_IfParameterIsNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Readability of unit test names", Scope = "member", Target = "~M:Unicorn.Impl.PdfSharp.Tests.Unit.FontDescriptorUnitTests.FontDescriptorClass_GetNormalSpaceWidthMethod_ThrowsArgumentNullExceptionWithCorrectParamNameProperty_IfParameterIsNull")]
